name: Terraform CI - Self Hosted Runner

run-name: Terraform CI | ${{ github.ref_name }} | ${{ github.actor }}

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validate and Plan

    runs-on: [self-hosted, Windows, X64]

    defaults:
      run:
        working-directory: terraform

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Check Terraform Version
        shell: powershell
        run: |
          terraform version

      - name: Terraform Format Check
        shell: powershell
        run: |
          terraform fmt -check

      - name: Terraform Init
        shell: powershell
        run: |
          terraform init

      - name: Terraform Validate
        shell: powershell
        run: |
          terraform validate

      - name: Terraform Plan
        shell: powershell
        run: |
          terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan
          retention-days: 5
          
  terraform-apply:
    name: Terraform Apply

    needs: terraform

    runs-on: [self-hosted, Windows, X64]

    environment: production

    defaults:
      run:
        working-directory: terraform

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Terraform Init
        shell: powershell
        run: |
          terraform init

      - name: Terraform Apply
        shell: powershell
        run: |
          terraform apply -auto-approve